export const vocab = [{word: "悪い", reading: "わるい", english: "bad", sentence: "目に悪いから暗いところで本を読んではいけない。",
sentReading: "め　に　わるい　から　くらい　ところ　で　ほん　を　よんで　は　いけない", engSent: "Because it is bad for your eyes, do not read under dim light."},
{word: "勝ち", reading: "かち", english: "win", sentence: "表が出たら僕の勝ち、裏が出たら君の勝ち。",
sentReading: "ひょう　が　でたら　ぼく　の　かち　うら　が　でたら　きみ　の　かち", engSent: "Heads it's my win, tails it's yours."},
{word: "思う", reading: "おもう", english: "to think", sentence: "試験が教育を駄目にしていると思う。",
sentReading: "しけん　が　きょういく　を　だめ　に　している　と　おもう", engSent: "I think exams are ruining education."},
{word: "仲間", reading: "なかま", english: "comrade", sentence: "彼は私の仕事仲間である。",
sentReading: "かれ　は　しごと　なかま　である", engSent: "He is my colleague."},
{word: "入れる", reading: "いれる", english: "to put in", sentence: "彼は大学に入れるように一所懸命勉強した。",
sentReading: "かれ　は　だいがく　に　いれる　ように　いっしょけんめい　べんきょうした", engSent: "He is my colleague."},
{word: "今", reading: "いま", english: "now", sentence: "列車は今着いたばかりです。",
sentReading: "れっしゃ　は　いま　ついた　ばらり　です", engSent: "The train has just arrived here."},
{word: "神", reading: "かみ", english: "God", sentence: "彼女は神を信じない。",
sentReading: "かのじょ　は　かみ　を　しんじない", engSent: "She doesn't believe in God."}];

export const shows = [{name: "Death Note", image: "deathnote.jpg"}, {name: "7 Seeds", image: "7seeds.jpg"},
{name: "Aggretsuko", image: "aggretsuko.jpg"}, {name: "A Silent Voice", image: "asilentvoice.jpg"},
{name: "Attack on Titan", image: "attackontitan.jpg"}, {name: "Blue Exorcist", image: "blueexorcist.jpg"},
{name: "Pokemon", image: "pokemon.jpg"}, {name: "Code Geass", image: "codegeass.jpg"},
{name: "Hunter x Hunter", image: "hunterxhunter.jpg"}, {name: "Ouran High School Host Club", image: "ouranhostclub.jpg"},
{name: "Bleach", image: "bleach.jpg"}, {name: "Vampire Knight", image: "vampireknight.jpg"}];
